### PR TITLE
feat: one-way-bind the `currentStep` property

### PR DESCRIPTION
**Pull request by alexlafroscia**
Replaces #136

### CODE REVIEW

**Comment by alexlafroscia** [comment]
@lougreenwood would you look this over and let me know if it solves the use-case you were going for around no longer supporting the two-way binding?

**Comment by alexlafroscia** [comment]
BTW @lougreenwood since this was originally your idea and I followed the implementation you did, I added you as a co-author of the changes 😄

**Comment by lougreenwood** [comment]
@alexlafroscia - I'm on vacation for the rest of this week, but will take a look in a few days! 👍

**Comment by alexlafroscia** [comment]
No worries -- take your time!

**Comment by lougreenwood** [comment]
hey @alexlafroscia  - just a head sup that I'm back and will be taking a look today or tomorrow. I've had a crazy busy couple of weeks

**Comment by lougreenwood** [comment]
@alexlafroscia I've just finished testing - all looks good - no issues to report 👍

**Comment by lougreenwood** [comment]
@alexlafroscia I'm going to go ahead and close #136 in favour of this and #148.

**Pull request merged**
