### PR TITLE
switch to classic ember structure

### PR DESCRIPTION
**Pull request by willrax**
Carrying on from #60 this changes the addon to use the classic structure. 

I was able to get it working in our application (it uses the pods structure) without any issues.

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Looks like you've got some failing tests there!

**Comment by willrax** [comment]
doh, didn't even notice. I'll get them fixed up today.

**Comment by willrax** [comment]
I noticed the test file structure was following the pods structure. Would you prefer to update that to reflect the classic structure as well or keep as is?

**Comment by alexlafroscia** [comment]
Sure, let's use the "classic" structure everywhere.

**Comment by alexlafroscia** [comment]
Thanks @willrax!

**Pull request merged**
